# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukt0kdGzVvPeDf0gc2YhGEZrosrHFcOt
"""

# =========================
# AML MVP v0.1 - Streamlit UI
# =========================

import streamlit as st
import pandas as pd
import numpy as np # pylint: disable=unused-import
import math
from html import escape
from difflib import SequenceMatcher
import re
import os
from pathlib import Path
import joblib

from datetime import datetime, timedelta

from sklearn.model_selection import train_test_split
from sklearn.utils import resample
from sklearn.preprocessing import LabelEncoder
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import classification_report, recall_score, precision_score, f1_score, average_precision_score

from xgboost import XGBClassifier
import shap


DEFAULT_ALERT_THRESHOLD = 0.20
DEFAULT_HIGH_THRESHOLD = 0.50
DEFAULT_CRITICAL_THRESHOLD = 0.75
SANCTION_POSSIBLE_MATCH_THRESHOLD = 82
SANCTION_STRONG_MATCH_THRESHOLD = 92
HKD_OCCASIONAL_CDD_THRESHOLD = 120000
HKD_WIRE_VA_THRESHOLD = 8000
BASE_DIR = Path(__file__).resolve().parent
DATA_PATH = BASE_DIR / "SAML-D.csv"
SANCTIONS_PATH = BASE_DIR / "sanctions_list.csv"
KYC_PATH = BASE_DIR / "kyc_profiles.csv"
BEST_PARAMS_PATH = BASE_DIR / "best_params.json"
AUDIT_LOG_PATH = BASE_DIR / "manual_override_audit.csv"
MODEL_BUNDLE_PATH = Path(
    os.getenv("AML_MODEL_BUNDLE_PATH", BASE_DIR / "aml_model_bundle.joblib")
).resolve()

# Load the complete dataset by default. Set AML_MAX_ROWS to a positive number
# when a smaller local sample is needed.
DEFAULT_LOCAL_MAX_ROWS = 0


# =========================
# PAGE CONFIG
# =========================
st.set_page_config(
    page_title="AML MVP v0.1",
    page_icon="💰",
    layout="wide"
)


st.markdown(
    """
    <style>
    :root {
        --aml-bg: #f6f8fb;
        --aml-panel: rgba(255, 255, 255, 0.92);
        --aml-line: rgba(31, 42, 68, 0.10);
        --aml-text: #182033;
        --aml-muted: #667085;
        --aml-blue: #2563eb;
        --aml-teal: #0f766e;
        --aml-cyan: #0891b2;
        --aml-amber: #b45309;
        --aml-red: #b42318;
        --aml-green: #15803d;
        --aml-shadow: 0 18px 50px rgba(31, 42, 68, 0.10);
    }

    .stApp {
        background:
            linear-gradient(180deg, #f8fafc 0%, var(--aml-bg) 48%, #eef3f8 100%);
        color: var(--aml-text);
    }

    .block-container {
        max-width: 1240px;
        padding-top: 2rem;
        padding-bottom: 3rem;
    }

    [data-testid="stSidebar"] {
        background: linear-gradient(180deg, #ffffff 0%, #f1f6fb 100%);
        border-right: 1px solid var(--aml-line);
    }

    [data-testid="stSidebar"] [data-testid="stMarkdownContainer"] {
        color: var(--aml-text);
    }

    .aml-hero {
        position: relative;
        overflow: hidden;
        padding: 30px 34px;
        border: 1px solid rgba(255, 255, 255, 0.68);
        border-radius: 8px;
        background:
            linear-gradient(135deg, rgba(13, 36, 69, 0.96), rgba(20, 83, 115, 0.92) 52%, rgba(15, 118, 110, 0.9));
        box-shadow: var(--aml-shadow);
        margin-bottom: 1.25rem;
    }

    .aml-hero:after {
        content: "";
        position: absolute;
        inset: 0;
        background-image:
            linear-gradient(rgba(255,255,255,0.07) 1px, transparent 1px),
            linear-gradient(90deg, rgba(255,255,255,0.07) 1px, transparent 1px);
        background-size: 34px 34px;
        mask-image: linear-gradient(90deg, rgba(0,0,0,0.42), transparent);
        pointer-events: none;
    }

    .aml-hero-content {
        position: relative;
        z-index: 1;
        max-width: 900px;
    }

    .aml-eyebrow {
        display: inline-flex;
        align-items: center;
        gap: 8px;
        padding: 5px 10px;
        border: 1px solid rgba(255, 255, 255, 0.22);
        border-radius: 999px;
        background: rgba(255,255,255,0.10);
        color: #d7fbff;
        font-size: 0.78rem;
        font-weight: 700;
        letter-spacing: 0;
        margin-bottom: 14px;
    }

    .aml-hero h1 {
        margin: 0 0 12px 0;
        color: #ffffff;
        font-size: 2.15rem;
        line-height: 1.16;
        letter-spacing: 0;
    }

    .aml-hero p {
        margin: 0;
        color: rgba(255,255,255,0.82);
        font-size: 1rem;
        line-height: 1.68;
    }

    .aml-section-label {
        margin: 1.2rem 0 0.65rem;
        color: var(--aml-text);
        font-size: 1.02rem;
        font-weight: 750;
        letter-spacing: 0;
    }

    .aml-soft-panel {
        padding: 16px 18px;
        border: 1px solid var(--aml-line);
        border-radius: 8px;
        background: var(--aml-panel);
        box-shadow: 0 10px 30px rgba(31, 42, 68, 0.06);
        margin: 0.75rem 0 1rem;
    }

    .aml-badge {
        display: inline-flex;
        align-items: center;
        min-height: 34px;
        padding: 6px 12px;
        border-radius: 999px;
        font-weight: 800;
        letter-spacing: 0;
        border: 1px solid;
        margin: 0.25rem 0 0.75rem;
    }

    .aml-badge-low {
        color: #166534;
        background: #dcfce7;
        border-color: #86efac;
    }

    .aml-badge-medium {
        color: #0f766e;
        background: #ccfbf1;
        border-color: #5eead4;
    }

    .aml-badge-high {
        color: #92400e;
        background: #fef3c7;
        border-color: #fbbf24;
    }

    .aml-badge-critical {
        color: #991b1b;
        background: #fee2e2;
        border-color: #fca5a5;
    }

    div[data-testid="stMetric"] {
        padding: 14px 16px;
        border: 1px solid var(--aml-line);
        border-radius: 8px;
        background: rgba(255, 255, 255, 0.86);
        box-shadow: 0 8px 24px rgba(31, 42, 68, 0.06);
    }

    div[data-testid="stMetricLabel"] p {
        color: var(--aml-muted);
        font-weight: 650;
    }

    div[data-testid="stMetricValue"] {
        color: var(--aml-text);
    }

    div[data-testid="stTabs"] button {
        border-radius: 8px 8px 0 0;
        color: var(--aml-muted);
        font-weight: 700;
    }

    div[data-testid="stTabs"] button[aria-selected="true"] {
        color: var(--aml-blue);
        background: rgba(37, 99, 235, 0.08);
    }

    .stButton > button {
        width: 100%;
        min-height: 46px;
        border: 0;
        border-radius: 8px;
        background: linear-gradient(135deg, #2563eb, #0891b2);
        color: white;
        font-weight: 800;
        box-shadow: 0 12px 30px rgba(37, 99, 235, 0.22);
    }

    .stButton > button:hover {
        border: 0;
        color: white;
        transform: translateY(-1px);
        box-shadow: 0 16px 34px rgba(37, 99, 235, 0.28);
    }

    div[data-baseweb="input"],
    div[data-baseweb="select"] > div,
    div[data-baseweb="textarea"] {
        border-radius: 8px;
        border-color: rgba(31, 42, 68, 0.16);
        background: rgba(255,255,255,0.94);
    }

    div[data-testid="stAlert"] {
        border-radius: 8px;
        border: 1px solid rgba(31, 42, 68, 0.10);
    }

    textarea {
        border-radius: 8px !important;
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace;
        line-height: 1.55;
    }

    h1, h2, h3 {
        letter-spacing: 0;
    }

    @media (max-width: 760px) {
        .block-container {
            padding-top: 1rem;
        }
        .aml-hero {
            padding: 22px 20px;
        }
        .aml-hero h1 {
            font-size: 1.55rem;
        }
    }
    </style>
    """,
    unsafe_allow_html=True,
)


# =========================
# 1. LOAD DATA
# =========================
@st.cache_data
def load_data():
    if not DATA_PATH.exists():
        raise FileNotFoundError(f"Dataset not found: {DATA_PATH}")

    configured_max_rows = int(os.getenv("AML_MAX_ROWS", DEFAULT_LOCAL_MAX_ROWS))
    max_rows = None if configured_max_rows <= 0 else configured_max_rows
    df = pd.read_csv(DATA_PATH, nrows=max_rows)
    return df


@st.cache_resource
def load_model_bundle(path, modified_time):
    del modified_time  # Included so Streamlit invalidates the cache on updates.
    return joblib.load(path)


force_model_training = os.getenv("AML_TRAIN_MODEL", "0") == "1"
model_bundle = None
if MODEL_BUNDLE_PATH.exists() and not force_model_training:
    model_bundle = load_model_bundle(
        str(MODEL_BUNDLE_PATH),
        MODEL_BUNDLE_PATH.stat().st_mtime,
    )

raw_df = model_bundle["sample_data"] if model_bundle else load_data()


# =========================
# 2. DATA PREPROCESSING
# =========================
@st.cache_data
def preprocess_data(df):
    df = df.copy()

    required_cols = [
        "Time", "Date", "Sender_account", "Receiver_account", "Amount",
        "Payment_currency", "Received_currency",
        "Sender_bank_location", "Receiver_bank_location",
        "Payment_type", "Is_laundering", "Laundering_type"
    ]

    missing_cols = [col for col in required_cols if col not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing columns in dataset: {missing_cols}")

    df = df.dropna(subset=["Is_laundering"])
    df["Is_laundering"] = df["Is_laundering"].astype(int)

    df["Time"] = pd.to_datetime(df["Time"], format="%H:%M:%S", errors="coerce")
    df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
    df = df.dropna(subset=["Time", "Date"])

    df["hour"] = df["Time"].dt.hour.astype(int)


    # -------------------------
    # Feature engineering
    # -------------------------
    df["is_cross_border"] = (
        df["Sender_bank_location"] != df["Receiver_bank_location"]
    ).astype(int)

    df["is_currency_mismatch"] = (
        df["Payment_currency"] != df["Received_currency"]
    ).astype(int)

    # -------------------------
    # Account-level graph features
    # -------------------------
    sender_out_degree = df.groupby("Sender_account")["Receiver_account"].transform("nunique")
    receiver_in_degree = df.groupby("Receiver_account")["Sender_account"].transform("nunique")

    df["fan_out_count"] = sender_out_degree
    df["fan_in_count"] = receiver_in_degree

    def map_pattern(row):
        if row["fan_in_count"] >= 3 and row["fan_out_count"] < 3:
            return "fan_in"
        elif row["fan_out_count"] >= 3 and row["fan_in_count"] < 3:
            return "fan_out"
        elif row["fan_in_count"] >= 3 and row["fan_out_count"] >= 3:
            return "fan_in_out"
        return "normal_flow"

    df["Transaction Pattern"] = df.apply(map_pattern, axis=1)

    # -------------------------
    # Sort chronologically
    # -------------------------
    df["txn_datetime"] = pd.to_datetime(
        df["Date"].dt.strftime("%Y-%m-%d") + " " + df["Time"].dt.strftime("%H:%M:%S"),
        errors="coerce"
    )
    df = df.sort_values("txn_datetime").reset_index(drop=True)

    # -------------------------
    # Enhanced feature engineering
    # -------------------------
    # Amount features
    df["log_amount"] = np.log1p(df["Amount"])
    df["is_round_amount"] = ((df["Amount"] % 1000 == 0) | (df["Amount"] % 10000 == 0)).astype(int)

    # Binary risk flags (from data analysis)
    df["is_cash_payment"] = df["Payment_type"].isin(["Cash Deposit", "Cash Withdrawal"]).astype(int)
    high_risk_currencies = ["Moroccan dirham", "Dirham"]
    df["is_high_risk_currency"] = (
        df["Payment_currency"].isin(high_risk_currencies) |
        df["Received_currency"].isin(high_risk_currencies)
    ).astype(int)

    # Cyclical time features
    df["hour_sin"] = np.sin(2 * np.pi * df["hour"] / 24)
    df["hour_cos"] = np.cos(2 * np.pi * df["hour"] / 24)
    df["day_of_week"] = df["Date"].dt.dayofweek
    df["is_weekend"] = (df["day_of_week"] >= 5).astype(int)
    df["is_business_hour"] = ((df["hour"] >= 9) & (df["hour"] <= 17)).astype(int)

    # Account velocity features (approximation via cumulative count)
    df = df.sort_values(["Sender_account", "txn_datetime"])
    df["sender_txn_seq_num"] = df.groupby("Sender_account").cumcount()
    df = df.sort_values(["Receiver_account", "txn_datetime"])
    df["receiver_txn_seq_num"] = df.groupby("Receiver_account").cumcount()
    df = df.sort_values("txn_datetime").reset_index(drop=True)

    # Amount anomaly relative to sender
    sender_stats = df.groupby("Sender_account")["Amount"].agg(["mean", "std"]).reset_index()
    sender_stats.columns = ["Sender_account", "sender_avg_amount", "sender_std_amount"]
    df = df.merge(sender_stats, on="Sender_account", how="left")
    df["amount_zscore_sender"] = (df["Amount"] - df["sender_avg_amount"]) / (df["sender_std_amount"] + 1)
    df["amount_ratio_sender"] = df["Amount"] / (df["sender_avg_amount"] + 1)
    df = df.drop(columns=["sender_avg_amount", "sender_std_amount"])

    # Interaction features
    df["cross_border_x_amount"] = df["is_cross_border"] * df["log_amount"]
    df["currency_mismatch_x_amount"] = df["is_currency_mismatch"] * df["log_amount"]
    df["cross_border_and_mismatch"] = (df["is_cross_border"] * df["is_currency_mismatch"]).astype(int)

    # -------------------------
    # Extract behavioural pattern from Laundering_type (without label leakage)
    # Strip "Normal_" prefix to get pure behavioural pattern;
    # fraud-specific patterns describe observable transaction behaviour
    # -------------------------
    df["laundering_pattern"] = df["Laundering_type"].str.replace(r"^Normal_", "", regex=True)

    # -------------------------
    # Keep target separately
    # -------------------------
    y = df["Is_laundering"].copy()

    # -------------------------
    # Keep account columns for reporting only
    # -------------------------
    report_df = df[["Sender_account", "Receiver_account", "Transaction Pattern"]].copy()
    model_df = df.drop(
        columns=[
            "Time",
            "Date",
            "Sender_account",
            "Receiver_account",
            "Laundering_type",
            "Is_laundering"
        ],
        errors="ignore"
    )

    categorical_cols = [
        "Payment_currency",
        "Received_currency",
        "Sender_bank_location",
        "Receiver_bank_location",
        "Payment_type",
        "Transaction Pattern",
        "laundering_pattern"
    ]

    encoders = {}
    for col in categorical_cols:
        le = LabelEncoder()
        model_df[col] = le.fit_transform(model_df[col].astype(str))
        encoders[col] = le

    for col in model_df.columns:
        model_df[col] = pd.to_numeric(model_df[col], errors="coerce")

    valid_idx = model_df.dropna().index
    model_df = model_df.loc[valid_idx].reset_index(drop=True)
    y = y.loc[valid_idx].reset_index(drop=True)
    report_df = report_df.loc[valid_idx].reset_index(drop=True)

    return model_df, y, report_df, encoders, categorical_cols


if model_bundle:
    model_df = y = report_df = None
    encoders = model_bundle["encoders"]
    categorical_cols = model_bundle["categorical_cols"]
else:
    model_df, y, report_df, encoders, categorical_cols = preprocess_data(raw_df)

@st.cache_resource
def train_model(model_df, y):
    full_df = model_df.copy()
    full_df["target"] = y

    # -------------------------
    # Time-based train/validation/test split (60/20/20)
    # -------------------------
    train_df, test_df = train_test_split(
        full_df,
        test_size=0.2,
        stratify=full_df["target"],
        random_state=42
    )

    fit_df, calibration_df = train_test_split(
        train_df,
        test_size=0.25,
        stratify=train_df["target"],
        random_state=42
    )

    # Cap calibration set for efficiency
    if len(calibration_df) > 100000:
        _, calibration_df = train_test_split(
            calibration_df,
            test_size=100000,
            stratify=calibration_df["target"],
            random_state=42
        )

    # Split fit_df into actual train and validation for early stopping
    fit_df, val_df = train_test_split(
        fit_df,
        test_size=0.15,
        stratify=fit_df["target"],
        random_state=42
    )

    # -------------------------
    # Target Encoding (smoothed fraud rate per category)
    # Computed ONLY on fit_df to prevent data leakage
    # -------------------------
    TARGET_ENCODE_COLS = [
        "Payment_currency", "Received_currency",
        "Sender_bank_location", "Receiver_bank_location",
        "Payment_type", "laundering_pattern"
    ]
    SMOOTHING = 100
    global_fraud_rate = fit_df["target"].mean()

    target_encodings = {}
    for col in TARGET_ENCODE_COLS:
        if col not in fit_df.columns:
            continue
        stats = fit_df.groupby(col)["target"].agg(["count", "mean"])
        stats["smoothed_rate"] = (
            (stats["count"] * stats["mean"] + SMOOTHING * global_fraud_rate)
            / (stats["count"] + SMOOTHING)
        )
        target_encodings[col] = stats["smoothed_rate"].to_dict()

    def apply_target_encoding(df, encodings, suffix="_risk"):
        df = df.copy()
        for col, mapping in encodings.items():
            if col in df.columns:
                df[f"{col}{suffix}"] = df[col].map(mapping).fillna(global_fraud_rate)
        return df

    fit_df = apply_target_encoding(fit_df, target_encodings)
    val_df = apply_target_encoding(val_df, target_encodings)
    calibration_df = apply_target_encoding(calibration_df, target_encodings)
    test_df = apply_target_encoding(test_df, target_encodings)

    # -------------------------
    # Improved sampling: 15:1 ratio (was 1:1, then capped at 5000)
    # -------------------------
    train_majority = fit_df[fit_df["target"] == 0]
    train_minority = fit_df[fit_df["target"] == 1]

    SAMPLING_RATIO = 15  # normal:fraud ratio after undersampling
    target_normal_count = min(len(train_majority), len(train_minority) * SAMPLING_RATIO)

    train_majority_downsampled = resample(
        train_majority,
        replace=False,
        n_samples=target_normal_count,
        random_state=42
    )

    train_balanced = pd.concat([train_majority_downsampled, train_minority])
    # NO MORE 5000-sample cap — we use all available data

    X_train = train_balanced.drop("target", axis=1)
    y_train = train_balanced["target"]

    X_val = val_df.drop("target", axis=1)
    y_val = val_df["target"]

    X_test = test_df.drop("target", axis=1)
    y_test = test_df["target"]

    # -------------------------
    # Improved XGBoost with scale_pos_weight + early stopping
    # -------------------------
    # Load tuned params if available, otherwise use defaults
    import json as _json
    if BEST_PARAMS_PATH.exists():
        with BEST_PARAMS_PATH.open("r", encoding="utf-8") as _f:
            tuned_params = _json.load(_f)
    else:
        tuned_params = {}

    xgb_params = {
        "n_estimators": tuned_params.get("n_estimators", 300),
        "max_depth": tuned_params.get("max_depth", 6),
        "learning_rate": tuned_params.get("learning_rate", 0.05),
        "subsample": tuned_params.get("subsample", 0.8),
        "colsample_bytree": tuned_params.get("colsample_bytree", 0.8),
        "min_child_weight": tuned_params.get("min_child_weight", 3),
        "reg_alpha": tuned_params.get("reg_alpha", 0.1),
        "reg_lambda": tuned_params.get("reg_lambda", 0.1),
        "scale_pos_weight": tuned_params.get("scale_pos_weight", SAMPLING_RATIO),
        "n_jobs": -1,
        "eval_metric": "aucpr",
        "tree_method": "hist",
        "random_state": 42
    }

    model = XGBClassifier(**xgb_params)

    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=False
    )

    # -------------------------
    # Probability calibration
    # -------------------------
    X_calibration = calibration_df.drop("target", axis=1)
    y_calibration = calibration_df["target"]

    scoring_model = CalibratedClassifierCV(
        estimator=model,
        method="sigmoid",
        cv=5
    )
    scoring_model.fit(X_calibration, y_calibration)

    # -------------------------
    # Evaluation metrics
    # -------------------------
    calibrated_scores = scoring_model.predict_proba(X_test)[:, 1]
    y_pred = (calibrated_scores >= DEFAULT_ALERT_THRESHOLD).astype(int)

    auprc = average_precision_score(y_test, calibrated_scores)

    # Alert rate: what % of transactions would be flagged at DEFAULT_ALERT_THRESHOLD
    alert_rate = y_pred.mean() * 100

    metrics = {
        "train_distribution": train_balanced["target"].value_counts().to_dict(),
        "calibration_distribution": calibration_df["target"].value_counts().to_dict(),
        "test_distribution": test_df["target"].value_counts().to_dict(),
        "recall": recall_score(y_test, y_pred),
        "precision": precision_score(y_test, y_pred, zero_division=0),
        "f1": f1_score(y_test, y_pred, zero_division=0),
        "auprc": auprc,
        "alert_rate": alert_rate,
        "num_train_samples": len(train_balanced),
        "classification_report": classification_report(y_test, y_pred, zero_division=0),
        "calibration_method": "Sigmoid probability calibration on a holdout set",
        "evaluation_threshold": DEFAULT_ALERT_THRESHOLD,
        "sampling_ratio": SAMPLING_RATIO
    }

    return model, scoring_model, X_train, X_test, y_test, metrics


if model_bundle:
    model = model_bundle["model"]
    scoring_model = model_bundle["scoring_model"]
    X_train = model_bundle["feature_schema"]
    X_test = y_test = None
    metrics = model_bundle["metrics"]
else:
    model, scoring_model, X_train, X_test, y_test, metrics = train_model(model_df, y)

    sample_data = pd.concat(
        [
            raw_df.head(2_000),
            raw_df[raw_df["Is_laundering"] == 1].head(200),
            raw_df[
                raw_df["Sender_bank_location"] != raw_df["Receiver_bank_location"]
            ].head(200),
        ],
        ignore_index=True,
    ).drop_duplicates()

    bundle_to_save = {
        "bundle_version": 1,
        "model": model,
        "scoring_model": scoring_model,
        "encoders": encoders,
        "categorical_cols": categorical_cols,
        "feature_schema": X_train.iloc[:0].copy(),
        "metrics": metrics,
        "sample_data": sample_data,
    }
    temporary_bundle_path = MODEL_BUNDLE_PATH.with_suffix(".joblib.tmp")
    joblib.dump(bundle_to_save, temporary_bundle_path, compress=3)
    temporary_bundle_path.replace(MODEL_BUNDLE_PATH)


# =========================
# 4. LANGUAGE AND CUSTOMER-FRIENDLY COPY
# =========================
LANGUAGES = {
    "繁體中文": "zh",
    "English": "en",
}

TEXT = {
    "zh": {
        "title": "💰 反洗錢交易風險偵測系統 — MVP v0.1",
        "intro": (
            "此 MVP 使用 SAML-D 交易資料作為示範及客戶測試資料。"
            "客戶可選用預設樣本或自行輸入交易資料，系統會給出校準後的模型警示分數、"
            "審查優先級、清楚解釋及一份可供內部合規審閱的草稿報告。"
        ),
        "tab_analysis": "交易分析",
        "tab_summary": "模型 / 資料摘要",
        "tab_doc": "MVP 測試說明",
        "language": "語言 / Language",
        "sample_header": "測試樣本",
        "sample_help": "選擇一個預設樣本，表單會自動帶入資料，方便客戶快速測試功能。",
        "sample_normal": "樣本 A：一般本地交易",
        "sample_cross_border": "樣本 B：跨境及幣種不同交易",
        "sample_laundering": "樣本 C：資料集中標記為可疑的交易",
        "manual_entry": "仍可直接修改下方欄位，測試不同交易情境。",
        "input_header": "輸入或調整交易資料",
        "sender_account": "付款方帳戶",
        "receiver_account": "收款方帳戶",
        "sender_name": "付款方姓名 / 公司名稱",
        "receiver_name": "收款方姓名 / 公司名稱",
        "amount": "交易金額",
        "hkd_equivalent_amount": "港元等值金額",
        "relationship_status": "客戶關係",
        "existing_customer": "已建立業務關係客戶",
        "occasional_non_customer": "非客戶一次性交易",
        "transfer_category": "交易類別",
        "other_transaction": "其他交易",
        "wire_transfer": "電匯",
        "virtual_asset_transfer": "虛擬資產轉賬",
        "hour": "交易時間（小時）",
        "payment_type": "付款方式",
        "sender_location": "付款方銀行地區",
        "receiver_location": "收款方銀行地區",
        "payment_currency": "付款幣種",
        "received_currency": "收款幣種",
        "fan_in": "收款方近期不同付款人數",
        "fan_out": "付款方近期不同收款人數",
        "transaction_pattern": "交易流向模式",
        "threshold_settings": "門檻設定",
        "module_subscription": "模組訂閱",
        "module_subscription_note": "銀行可根據已有系統選擇啟用模組，形成按需付費的部署方式。",
        "module_kyc": "KYC 客戶資料",
        "module_transaction_monitoring": "交易監控 AI",
        "module_sanctions": "制裁名單篩查",
        "module_str": "STR 草稿生成",
        "module_manual_review": "人工干預與審計",
        "module_disabled": "此模組未啟用。",
        "alert_threshold": "警示門檻",
        "high_threshold": "高風險門檻",
        "critical_threshold": "Critical / T+1 門檻",
        "priority_logic": (
            "**MVP 優先級規則**\n"
            "- Low：低於警示門檻，不產生警示\n"
            "- Medium：達到警示門檻，T+5 審查\n"
            "- High：高風險，T+5 優先審查\n"
            "- Critical：最高風險，T+1 優先審查"
        ),
        "analyze": "分析交易",
        "analyzing": "正在分析交易...",
        "risk_score": "校準後模型警示分數",
        "risk_level": "風險等級",
        "sanction_screening": "制裁名單篩查",
        "entity_view": "KYC 實體視圖",
        "transaction_view": "交易視圖",
        "kyc_link_note": "系統使用帳戶號作為唯一標識，把交易資料與 KYC Profile 關聯，方便同時查看「這筆交易」和「交易背後的客戶」。",
        "customer_id": "客戶 ID",
        "customer_type": "客戶類型",
        "country": "國家 / 地區",
        "industry": "行業",
        "kyc_risk_level": "KYC 風險",
        "pep_status": "PEP 狀態",
        "onboarding_date": "開戶日期",
        "expected_volume": "預期月交易量",
        "profile_missing": "未找到 KYC Profile",
        "kyc_override_reason": "KYC Profile 為高風險客戶",
        "screening_result": "篩查結果",
        "no_sanction_match": "No Match / 未命中",
        "possible_sanction_match": "Possible Match / 可能命中",
        "strong_sanction_match": "Strong Match / 高度命中",
        "screening_note": "此 MVP 使用本地 demo 制裁名單和模糊名稱匹配；正式版本應接入官方或商業制裁資料源。",
        "matched_party": "命中方",
        "matched_name": "名單名稱",
        "match_score": "匹配分數",
        "list_source": "名單來源",
        "risk_type": "風險類型",
        "screening_action_none": "未發現制裁名單相似命中，按 AML 模型結果處理。",
        "screening_action_possible": "發現可能命中，建議合規人員核對身份資料、別名、國籍及公司註冊資料。",
        "screening_action_strong": "發現高度命中，建議立即升級為 Critical 並進行人工覆核。",
        "rules_engine": "香港硬編碼規則引擎",
        "rules_result": "規則觸發結果",
        "rules_clear": "未觸發硬性規則",
        "rule_120k_title": "120,000 HKD 非客戶一次性交易 CDD 觸發",
        "rule_120k_action": "強制拦截並觸發全面客戶盡職審查（CDD）。",
        "rule_8k_title": "8,000 HKD 電匯 / 虛擬資產轉賬觸發",
        "rule_8k_action": "觸發身份核實與轉賬記錄捕獲。",
        "rules_note": "MVP 規則引擎以港元等值金額計算；如原始交易不是 HKD，應由正式系統接入匯率服務後換算。",
        "low": "Low / 低",
        "medium": "Medium / 中",
        "high": "High / 高",
        "critical": "Critical / 重大",
        "score_note": "此分數經過概率校準，用於排序和優先審查；它不代表交易一定違規。",
        "no_alert": "✅ 未觸發警示",
        "no_alert_explain": "此交易低於目前警示門檻。系統不會為此交易產生可疑交易報告草稿。",
        "alert": "🚨 已觸發警示",
        "priority": "優先級",
        "deadline": "審查期限",
        "priority_reason": "優先原因",
        "manual_intervention": "人工干預",
        "manual_intervention_note": "高級管理人員可手動調整 AI 風險等級；每次修改都會保存操作者、時間、原因和調整前後結果。",
        "manager_name": "管理人員姓名",
        "manager_role": "管理人員角色",
        "override_level": "調整後風險等級",
        "override_reason": "調整原因",
        "apply_override": "保存人工調整",
        "override_saved": "人工調整已保存至審計軌跡。",
        "override_reason_required": "請填寫管理人員姓名和調整原因。",
        "audit_trail": "審計軌跡",
        "original_level": "原風險等級",
        "final_level": "最終風險等級",
        "very_high_model_risk": "模型風險分數非常高",
        "sanction_strong_reason": "制裁名單高度命中",
        "sanction_possible_reason": "制裁名單可能命中",
        "high_model_risk": "模型警示分數偏高",
        "standard_alert": "標準可疑交易警示",
        "why_flagged": "為什麼系統提示此交易？",
        "plain_explanation_intro": (
            "以下列出最影響判斷的因素。紅色代表該因素提高風險，"
            "綠色代表該因素降低風險；分數只表示影響方向和相對強度，"
            "不等同於金額或概率。"
        ),
        "increases_risk": "提高風險",
        "reduces_risk": "降低風險",
        "impact": "影響值",
        "report_label": "客戶友好的風險報告草稿",
        "dataset_used": "使用資料集",
        "dataset_note": "SAML-D.csv 會作為示範及試點測試資料；頁面中的測試樣本亦由此資料集抽取。",
        "training_strategy": "訓練 / 測試策略",
        "balanced_training": "平衡後訓練資料分佈",
        "calibration_distribution": "概率校準資料分佈",
        "real_test": "真實測試資料分佈",
        "design_choice": (
            "**設計說明：** 訓練階段會下採樣一般交易，使模型有足夠機會學習可疑交易特徵；"
            "之後再用保留原始比例的校準資料修正分數，避免模型過度自信；"
            "測試階段亦保留原始不平衡比例，較接近實際 AML 場景。"
        ),
        "model": "模型",
        "algorithm": "演算法：XGBoost 分類模型",
        "metrics": "評估指標",
        "recall_help": "召回率越高，代表越少漏掉可疑交易；AML 場景通常更重視召回率。",
        "calibration_help": "頁面顯示的是校準後模型警示分數，並以 Low / Medium / High / Critical 呈現，方便非技術客戶理解。",
        "classification_report": "分類報告（技術附錄）",
        "test_doc": """
## 1. 測試目標

本 MVP 旨在驗證一個基本的反洗錢決策支援流程：輸入交易、取得校準後模型警示分數及風險等級、理解提示原因，並生成可供合規人員審閱的可疑交易報告草稿。

---

## 2. 客戶可測試功能

### 功能 1：一鍵測試樣本

客戶可在「測試樣本」中選擇一般交易、跨境交易或資料集中已標記的可疑交易。選取後，系統會自動帶入表單欄位，方便快速驗證流程。

### 功能 2：即時交易分析

客戶可修改姓名、金額、地區、幣種、付款方式及交易流向等欄位。按下分析後，系統會返回制裁名單篩查結果、校準後模型警示分數、風險等級及是否觸發警示。

### 功能 3：香港硬編碼規則引擎

系統內置香港市場核心觸發線：非客戶一次性交易達 120,000 HKD 會強制觸發全面 CDD；電匯或虛擬資產轉賬達 8,000 HKD 會觸發身份核實與轉賬記錄捕獲。

### 功能 4：KYC 與交易資料聯動

系統會使用帳戶號作為唯一標識，把付款方與收款方帳戶連接到 KYC Profile，展示客戶 ID、客戶類型、國家、行業、KYC 風險等級、PEP 狀態及預期月交易量。

### 功能 5：審查優先級

系統會按校準後模型警示分數分為 Low、Medium、High、Critical。Critical 會分配 T+1 審查，其餘警示級別會分配 T+5 審查。此 MVP 已加入 demo 制裁名單篩查，但尚未接入 PEP 名單或官方高風險司法管轄區資料。

### 功能 6：制裁名單篩查

系統會把付款方及收款方姓名與本地 demo 制裁名單做模糊匹配，輸出 No Match、Possible Match 或 Strong Match。Strong Match 會直接升級為 Critical；Possible Match 會升級為 High 以便人工覆核。

### 功能 7：簡明解釋

系統會把模型判斷拆成容易理解的因素，例如是否跨境、幣種是否不同、交易金額、交易時間及帳戶流向模式。這讓非技術客戶也能理解為何交易被提示。

### 功能 8：風險報告草稿

觸發警示後，系統會生成一份客戶友好的報告草稿，包含交易摘要、風險判斷、主要原因、建議下一步及重要限制聲明。

### 功能 9：人工干預與審計軌跡

高級管理人員可在分析後手動調整 AI 風險等級，並必須填寫調整原因。系統會記錄誰、何時、為何修改，以及修改前後的風險等級。

### 功能 10：模組化訂閱架構

銀行可按自身已有系統選擇啟用 KYC、交易監控、制裁名單篩查、STR 草稿生成、人工干預與審計等模組。未訂閱的模組不參與頁面展示和風險覆蓋邏輯，方便按需付費與分階段導入。

---

## 3. MVP 限制

- 目前只使用 demo 制裁名單，尚未接入真實官方或商業制裁資料源。
- 尚未接入 PEP 名單。
- 尚未接入負面新聞或外部情報資料。
- 尚未加入官方高風險地區規則。
- 報告是決策支援輸出，不是自動監管申報。

---

## 4. 後續改進

- 接入制裁、PEP 及高風險地區資料源。
- 加入批量 CSV 上傳。
- 加入案件管理、審批流程及審計日誌。
- 加入模型監控及持續校準功能。
""",
    },
    "en": {
        "title": "💰 AML Transaction Risk Detection System — MVP v0.1",
        "intro": (
            "This MVP uses the SAML-D transaction dataset as demo and pilot-testing data. "
            "Clients can use ready-made samples or enter their own transaction details. "
            "The system returns a calibrated model alert score, review priority, plain-language explanation, "
            "and a draft report for internal compliance review."
        ),
        "tab_analysis": "Transaction Analysis",
        "tab_summary": "Model / Dataset Summary",
        "tab_doc": "MVP Test Guide",
        "language": "Language / 語言",
        "sample_header": "Test Samples",
        "sample_help": "Choose a ready-made sample to auto-fill the form for quick client testing.",
        "sample_normal": "Sample A: Typical domestic transaction",
        "sample_cross_border": "Sample B: Cross-border and currency mismatch",
        "sample_laundering": "Sample C: Dataset-labelled suspicious transaction",
        "manual_entry": "You can still edit any field below to test different scenarios.",
        "input_header": "Enter or Adjust Transaction Details",
        "sender_account": "Sender Account",
        "receiver_account": "Receiver Account",
        "sender_name": "Sender Name / Company",
        "receiver_name": "Receiver Name / Company",
        "amount": "Amount",
        "hkd_equivalent_amount": "HKD Equivalent Amount",
        "relationship_status": "Customer Relationship",
        "existing_customer": "Existing Business Relationship",
        "occasional_non_customer": "Occasional Non-Customer Transaction",
        "transfer_category": "Transaction Category",
        "other_transaction": "Other Transaction",
        "wire_transfer": "Wire Transfer",
        "virtual_asset_transfer": "Virtual Asset Transfer",
        "hour": "Transaction Hour",
        "payment_type": "Payment Type",
        "sender_location": "Sender Bank Location",
        "receiver_location": "Receiver Bank Location",
        "payment_currency": "Payment Currency",
        "received_currency": "Received Currency",
        "fan_in": "Receiver's Recent Unique Senders",
        "fan_out": "Sender's Recent Unique Receivers",
        "transaction_pattern": "Transaction Flow Pattern",
        "threshold_settings": "Threshold Settings",
        "module_subscription": "Module Subscription",
        "module_subscription_note": "Banks can enable only the modules they need, supporting modular deployment and pay-as-needed pricing.",
        "module_kyc": "KYC Customer Profiles",
        "module_transaction_monitoring": "Transaction Monitoring AI",
        "module_sanctions": "Sanction Screening",
        "module_str": "STR Draft Generation",
        "module_manual_review": "Manual Intervention and Audit",
        "module_disabled": "This module is not enabled.",
        "alert_threshold": "Alert Threshold",
        "high_threshold": "High Risk Threshold",
        "critical_threshold": "Critical / T+1 Threshold",
        "priority_logic": (
            "**MVP Priority Logic**\n"
            "- Low: below alert threshold, no alert\n"
            "- Medium: reaches alert threshold, T+5 review\n"
            "- High: high risk, priority T+5 review\n"
            "- Critical: highest risk, T+1 priority review"
        ),
        "analyze": "Analyze Transaction",
        "analyzing": "Analyzing transaction...",
        "risk_score": "Calibrated Model Alert Score",
        "risk_level": "Risk Level",
        "sanction_screening": "Sanction Screening",
        "entity_view": "KYC Entity View",
        "transaction_view": "Transaction View",
        "kyc_link_note": "The system uses account number as a unique identifier to link transaction data with KYC Profiles, so users can review both the transaction and the customers behind it.",
        "customer_id": "Customer ID",
        "customer_type": "Customer Type",
        "country": "Country / Region",
        "industry": "Industry",
        "kyc_risk_level": "KYC Risk",
        "pep_status": "PEP Status",
        "onboarding_date": "Onboarding Date",
        "expected_volume": "Expected Monthly Volume",
        "profile_missing": "KYC Profile Not Found",
        "kyc_override_reason": "High-risk KYC profile",
        "screening_result": "Screening Result",
        "no_sanction_match": "No Match",
        "possible_sanction_match": "Possible Match",
        "strong_sanction_match": "Strong Match",
        "screening_note": "This MVP uses a local demo sanctions list and fuzzy name matching. A production version should connect to official or commercial sanctions sources.",
        "matched_party": "Matched Party",
        "matched_name": "Matched Name",
        "match_score": "Match Score",
        "list_source": "List Source",
        "risk_type": "Risk Type",
        "screening_action_none": "No similar sanctions-list match was found. Continue based on the AML model result.",
        "screening_action_possible": "A possible match was found. Compliance should verify identity details, aliases, nationality, and company registration records.",
        "screening_action_strong": "A strong match was found. Escalate to Critical and perform manual compliance review immediately.",
        "rules_engine": "Hong Kong Hardcoded Rules Engine",
        "rules_result": "Rules Result",
        "rules_clear": "No hardcoded rule triggered",
        "rule_120k_title": "HKD 120,000 Occasional Non-Customer CDD Trigger",
        "rule_120k_action": "Block the transaction and trigger full customer due diligence (CDD).",
        "rule_8k_title": "HKD 8,000 Wire / Virtual Asset Transfer Trigger",
        "rule_8k_action": "Trigger identity verification and transfer record capture.",
        "rules_note": "The MVP rules engine uses HKD equivalent amount. For non-HKD transactions, production systems should integrate an FX conversion service.",
        "low": "Low",
        "medium": "Medium",
        "high": "High",
        "critical": "Critical",
        "score_note": "This calibrated score is used for ranking and review priority. It does not mean the transaction is definitely unlawful.",
        "no_alert": "✅ No Alert",
        "no_alert_explain": "This transaction is below the current alert threshold. No draft suspicious transaction report is generated.",
        "alert": "🚨 Alert Triggered",
        "priority": "Priority",
        "deadline": "Review Deadline",
        "priority_reason": "Priority Reason",
        "manual_intervention": "Manual Intervention",
        "manual_intervention_note": "Senior management can manually adjust the AI risk level. Every change records who changed it, when it changed, why it changed, and the before/after result.",
        "manager_name": "Manager Name",
        "manager_role": "Manager Role",
        "override_level": "Adjusted Risk Level",
        "override_reason": "Reason for Adjustment",
        "apply_override": "Save Manual Adjustment",
        "override_saved": "Manual adjustment saved to the audit trail.",
        "override_reason_required": "Please enter manager name and adjustment reason.",
        "audit_trail": "Audit Trail",
        "original_level": "Original Risk Level",
        "final_level": "Final Risk Level",
        "very_high_model_risk": "Very high model risk score",
        "sanction_strong_reason": "Strong sanctions-list match",
        "sanction_possible_reason": "Possible sanctions-list match",
        "high_model_risk": "High model alert score",
        "standard_alert": "Standard suspicious transaction alert",
        "why_flagged": "Why was this transaction flagged?",
        "plain_explanation_intro": (
            "The factors below had the strongest influence on the result. Red means the factor increased risk; "
            "green means it reduced risk. The impact value shows direction and relative strength, not a cash amount or probability."
        ),
        "increases_risk": "Increases risk",
        "reduces_risk": "Reduces risk",
        "impact": "Impact",
        "report_label": "Client-Friendly Draft Risk Report",
        "dataset_used": "Dataset Used",
        "dataset_note": "SAML-D.csv is used as demo and pilot-testing data; the test samples on this page are selected from the same dataset.",
        "training_strategy": "Training / Testing Strategy",
        "balanced_training": "Balanced Training Distribution",
        "calibration_distribution": "Probability Calibration Distribution",
        "real_test": "Real Test Distribution",
        "design_choice": (
            "**Design note:** The training set is downsampled so the model can learn suspicious patterns; "
            "a separate calibration set with the original distribution then adjusts the score to reduce overconfidence; "
            "the test set also keeps the original imbalanced distribution to better reflect a real AML environment."
        ),
        "model": "Model",
        "algorithm": "Algorithm: XGBoost Classifier",
        "metrics": "Evaluation Metrics",
        "recall_help": "Higher recall means fewer suspicious transactions are missed. AML workflows usually prioritize recall.",
        "calibration_help": "The page shows a calibrated model alert score and Low / Medium / High / Critical risk level so non-technical clients can interpret the result more easily.",
        "classification_report": "Classification Report (Technical Appendix)",
        "test_doc": """
## 1. Objective

This MVP validates a basic AML decision-support workflow: enter a transaction, receive a calibrated model alert score and risk level, understand the reason for the alert, and generate a draft suspicious transaction report for compliance review.

---

## 2. Features Clients Can Test

### Feature 1: Ready-Made Test Samples

Clients can choose a typical domestic transaction, a cross-border transaction, or a dataset-labelled suspicious transaction. The form is auto-filled so the workflow can be tested immediately.

### Feature 2: Real-Time Transaction Analysis

Clients can edit names, amount, locations, currencies, payment type, and transaction flow fields. After analysis, the system returns a sanctions screening result, a calibrated model alert score, a risk level, and an alert decision.

### Feature 3: Hong Kong Hardcoded Rules Engine

The system includes Hong Kong core trigger lines: occasional non-customer transactions at HKD 120,000 trigger full CDD, while wire or virtual asset transfers at HKD 8,000 trigger identity verification and transfer record capture.

### Feature 4: KYC and Transaction Data Linkage

The system uses account number as a unique identifier to connect sender and receiver accounts to KYC Profiles, showing customer ID, customer type, country, industry, KYC risk level, PEP status, and expected monthly volume.

### Feature 5: Review Priority

The system maps the calibrated model alert score into Low, Medium, High, and Critical. Critical receives a T+1 review deadline, while other alert levels receive T+5 review. This MVP now includes demo sanctions screening, but it does not yet connect to PEP or official high-risk jurisdiction data.

### Feature 6: Sanction Screening

The system compares sender and receiver names with a local demo sanctions list using fuzzy matching. It returns No Match, Possible Match, or Strong Match. Strong Match is escalated to Critical; Possible Match is escalated to High for manual review.

### Feature 7: Plain-Language Explanation

The system translates the model's decision into understandable factors, such as cross-border status, currency mismatch, amount, transaction time, and account flow pattern. This helps non-technical clients understand why an alert was raised.

### Feature 8: Draft Risk Report

When an alert is triggered, the system generates a client-friendly draft report with a transaction summary, risk decision, key reasons, recommended next steps, and important limitations.

### Feature 9: Manual Intervention and Audit Trail

Senior management can manually adjust the AI risk level after analysis and must provide a reason. The system records who changed it, when it changed, why it changed, and the before/after risk levels.

### Feature 10: Modular Subscription Architecture

Banks can enable KYC, transaction monitoring, sanction screening, STR draft generation, and manual review modules based on their existing systems. Disabled modules do not participate in the UI or risk override logic, supporting pay-as-needed adoption and phased rollout.

---

## 3. MVP Limitations

- A demo sanctions list is used, but no live official or commercial sanctions source is integrated.
- No PEP database is integrated.
- No adverse media or external intelligence is integrated.
- No official high-risk jurisdiction rules are integrated.
- The report is decision support, not an automatic regulatory filing.

---

## 4. Future Improvements

- Integrate sanctions, PEP, and high-risk jurisdiction sources.
- Add batch CSV upload.
- Add case management, approval workflow, and audit logs.
- Add model monitoring and ongoing calibration.
""",
    },
}

FEATURE_LABELS = {
    "zh": {
        "Amount": "交易金額",
        "Payment_currency": "付款幣種",
        "Received_currency": "收款幣種",
        "Sender_bank_location": "付款方銀行地區",
        "Receiver_bank_location": "收款方銀行地區",
        "Payment_type": "付款方式",
        "hour": "交易時間",
        "is_cross_border": "是否跨境",
        "is_currency_mismatch": "付款與收款幣種是否不同",
        "fan_in_count": "收款方近期不同付款人數",
        "fan_out_count": "付款方近期不同收款人數",
        "Transaction Pattern": "交易流向模式",
    },
    "en": {
        "Amount": "Amount",
        "Payment_currency": "Payment currency",
        "Received_currency": "Received currency",
        "Sender_bank_location": "Sender bank location",
        "Receiver_bank_location": "Receiver bank location",
        "Payment_type": "Payment type",
        "hour": "Transaction hour",
        "is_cross_border": "Cross-border transaction",
        "is_currency_mismatch": "Currency mismatch",
        "fan_in_count": "Receiver's recent unique senders",
        "fan_out_count": "Sender's recent unique receivers",
        "Transaction Pattern": "Transaction flow pattern",
    },
}


def tr(key, lang):
    return TEXT[lang][key]


def yn(value, lang):
    return ("是" if int(value) else "否") if lang == "zh" else ("Yes" if int(value) else "No")


def get_risk_level(risk_score, alert_threshold, high_threshold, critical_threshold):
    if risk_score < alert_threshold:
        return "low"
    if risk_score < high_threshold:
        return "medium"
    if risk_score < critical_threshold:
        return "high"
    return "critical"


def apply_sanction_override(model_level, screening_result):
    if screening_result["status"] == "strong":
        return "critical"
    if screening_result["status"] == "possible" and model_level in ["low", "medium"]:
        return "high"
    return model_level


def apply_kyc_override(current_level, sender_profile, receiver_profile):
    risk_values = [
        str(sender_profile.get("kyc_risk_level", "")).lower(),
        str(receiver_profile.get("kyc_risk_level", "")).lower(),
    ]
    pep_values = [
        str(sender_profile.get("pep_status", "")).lower(),
        str(receiver_profile.get("pep_status", "")).lower(),
    ]
    if "yes" in pep_values and current_level in ["low", "medium", "high"]:
        return "critical"
    if "high" in risk_values and current_level in ["low", "medium"]:
        return "high"
    return current_level


def evaluate_hk_rules(hkd_amount, relationship_status, transfer_category, lang):
    triggered = []
    if relationship_status == "occasional_non_customer" and hkd_amount >= HKD_OCCASIONAL_CDD_THRESHOLD:
        triggered.append({
            "code": "HK_120K_OCCASIONAL_CDD",
            "title": tr("rule_120k_title", lang),
            "action": tr("rule_120k_action", lang),
            "severity": "critical",
        })

    if transfer_category in ["wire_transfer", "virtual_asset_transfer"] and hkd_amount >= HKD_WIRE_VA_THRESHOLD:
        triggered.append({
            "code": "HK_8K_WIRE_VA_RECORD",
            "title": tr("rule_8k_title", lang),
            "action": tr("rule_8k_action", lang),
            "severity": "high",
        })

    return triggered


def apply_rules_override(current_level, triggered_rules):
    if any(rule["severity"] == "critical" for rule in triggered_rules):
        return "critical"
    if triggered_rules and current_level in ["low", "medium"]:
        return "high"
    return current_level


def get_priority_for_level(level, lang, screening_result=None, sender_profile=None, receiver_profile=None):
    now = datetime.now()
    if screening_result and screening_result["status"] == "strong":
        return "T+1", now + timedelta(days=1), tr("sanction_strong_reason", lang)
    if screening_result and screening_result["status"] == "possible":
        return "T+5", now + timedelta(days=5), tr("sanction_possible_reason", lang)
    profiles = [sender_profile or {}, receiver_profile or {}]
    if any(str(profile.get("pep_status", "")).lower() == "yes" for profile in profiles):
        return "T+1", now + timedelta(days=1), tr("kyc_override_reason", lang)
    if any(str(profile.get("kyc_risk_level", "")).lower() == "high" for profile in profiles):
        return "T+5", now + timedelta(days=5), tr("kyc_override_reason", lang)
    if level == "critical":
        return "T+1", now + timedelta(days=1), tr("very_high_model_risk", lang)
    if level == "high":
        return "T+5", now + timedelta(days=5), tr("high_model_risk", lang)
    return "T+5", now + timedelta(days=5), tr("standard_alert", lang)


@st.cache_data
def load_sanctions_data():
    try:
        sanctions_df = pd.read_csv(SANCTIONS_PATH)
    except FileNotFoundError:
        sanctions_df = pd.DataFrame(
            columns=["name", "alias", "country", "list_source", "risk_type"]
        )
    return sanctions_df.fillna("")


@st.cache_data
def load_kyc_profiles():
    try:
        kyc_df = pd.read_csv(KYC_PATH, dtype={"account_id": str})
    except FileNotFoundError:
        kyc_df = pd.DataFrame(
            columns=[
                "account_id", "customer_id", "legal_name", "customer_type",
                "country", "industry", "kyc_risk_level", "pep_status",
                "onboarding_date", "expected_monthly_volume"
            ]
        )
    kyc_df["account_id"] = kyc_df["account_id"].astype(str)
    return kyc_df.fillna("")


def get_kyc_profile(account_id, kyc_df):
    matches = kyc_df[kyc_df["account_id"].astype(str) == str(account_id)]
    if matches.empty:
        return {
            "account_id": str(account_id),
            "customer_id": "N/A",
            "legal_name": "",
            "customer_type": "N/A",
            "country": "N/A",
            "industry": "N/A",
            "kyc_risk_level": "Unknown",
            "pep_status": "Unknown",
            "onboarding_date": "N/A",
            "expected_monthly_volume": "N/A",
            "profile_found": False,
        }
    profile = matches.iloc[0].to_dict()
    profile["profile_found"] = True
    return profile


def profile_name(profile, fallback_name):
    return profile.get("legal_name") or fallback_name


def render_profile_card(title, profile, lang):
    if not profile.get("profile_found"):
        st.warning(f"{title}: {tr('profile_missing', lang)}")
        return
    cols = st.columns(4)
    cols[0].metric(tr("customer_id", lang), profile["customer_id"])
    cols[1].metric(tr("customer_type", lang), profile["customer_type"])
    cols[2].metric(tr("country", lang), profile["country"])
    cols[3].metric(tr("kyc_risk_level", lang), profile["kyc_risk_level"])
    cols = st.columns(4)
    cols[0].metric(tr("industry", lang), profile["industry"])
    cols[1].metric(tr("pep_status", lang), profile["pep_status"])
    cols[2].metric(tr("onboarding_date", lang), profile["onboarding_date"])
    cols[3].metric(tr("expected_volume", lang), profile["expected_monthly_volume"])


def normalize_name(value):
    value = str(value).lower()
    value = re.sub(r"[^a-z0-9 ]+", " ", value)
    return re.sub(r"\s+", " ", value).strip()


def name_similarity(left, right):
    left = normalize_name(left)
    right = normalize_name(right)
    if not left or not right:
        return 0
    if left == right:
        return 100
    return round(SequenceMatcher(None, left, right).ratio() * 100)


def screen_party(party_label, party_name, sanctions_df):
    best = {
        "party": party_label,
        "input_name": party_name,
        "matched_name": "",
        "country": "",
        "list_source": "",
        "risk_type": "",
        "score": 0,
    }

    for _, sanction in sanctions_df.iterrows():
        candidates = [sanction.get("name", ""), sanction.get("alias", "")]
        score = max(name_similarity(party_name, candidate) for candidate in candidates)
        if score > best["score"]:
            best.update({
                "matched_name": sanction.get("name", ""),
                "country": sanction.get("country", ""),
                "list_source": sanction.get("list_source", ""),
                "risk_type": sanction.get("risk_type", ""),
                "score": score,
            })

    return best


def screen_sanctions(sender_name, receiver_name, sanctions_df):
    sender_match = screen_party("sender", sender_name, sanctions_df)
    receiver_match = screen_party("receiver", receiver_name, sanctions_df)
    best_match = max([sender_match, receiver_match], key=lambda item: item["score"])

    if best_match["score"] >= SANCTION_STRONG_MATCH_THRESHOLD:
        status = "strong"
    elif best_match["score"] >= SANCTION_POSSIBLE_MATCH_THRESHOLD:
        status = "possible"
    else:
        status = "none"

    return {
        "status": status,
        "best_match": best_match,
        "all_matches": [sender_match, receiver_match],
    }


def no_screening_result():
    empty_match = {
        "party": "N/A",
        "input_name": "",
        "matched_name": "",
        "country": "",
        "list_source": "",
        "risk_type": "",
        "score": 0,
    }
    return {
        "status": "none",
        "best_match": empty_match,
        "all_matches": [empty_match],
    }


def empty_kyc_profile(account_id):
    return {
        "account_id": str(account_id),
        "customer_id": "N/A",
        "legal_name": "",
        "customer_type": "N/A",
        "country": "N/A",
        "industry": "N/A",
        "kyc_risk_level": "Unknown",
        "pep_status": "Unknown",
        "onboarding_date": "N/A",
        "expected_monthly_volume": "N/A",
        "profile_found": False,
    }


def screening_label(screening_result, lang):
    labels = {
        "none": tr("no_sanction_match", lang),
        "possible": tr("possible_sanction_match", lang),
        "strong": tr("strong_sanction_match", lang),
    }
    return labels[screening_result["status"]]


def screening_action(screening_result, lang):
    actions = {
        "none": tr("screening_action_none", lang),
        "possible": tr("screening_action_possible", lang),
        "strong": tr("screening_action_strong", lang),
    }
    return actions[screening_result["status"]]


def party_display(party, lang):
    if party not in ["sender", "receiver"]:
        return "N/A"
    if lang == "zh":
        return "付款方" if party == "sender" else "收款方"
    return "Sender" if party == "sender" else "Receiver"


def risk_level_options(lang):
    return {
        tr("low", lang): "low",
        tr("medium", lang): "medium",
        tr("high", lang): "high",
        tr("critical", lang): "critical",
    }


def risk_level_display(level, lang):
    return tr(level, lang)


def append_audit_record(record):
    columns = [
        "timestamp", "manager_name", "manager_role", "sender_account",
        "receiver_account", "original_risk_level", "new_risk_level",
        "risk_score", "reason"
    ]
    audit_df = pd.DataFrame([record], columns=columns)
    write_header = not os.path.exists(AUDIT_LOG_PATH)
    audit_df.to_csv(AUDIT_LOG_PATH, mode="a", header=write_header, index=False)


@st.cache_data
def load_audit_trail():
    if not os.path.exists(AUDIT_LOG_PATH):
        return pd.DataFrame(
            columns=[
                "timestamp", "manager_name", "manager_role", "sender_account",
                "receiver_account", "original_risk_level", "new_risk_level",
                "risk_score", "reason"
            ]
        )
    return pd.read_csv(AUDIT_LOG_PATH)


def render_hero(lang):
    eyebrow = "AI AML Decision Support" if lang == "en" else "AI 反洗錢決策支援"
    st.markdown(
        f"""
        <div class="aml-hero">
            <div class="aml-hero-content">
                <div class="aml-eyebrow">{escape(eyebrow)}</div>
                <h1>{escape(tr("title", lang))}</h1>
                <p>{escape(tr("intro", lang))}</p>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def section_label(text):
    st.markdown(
        f'<div class="aml-section-label">{escape(text)}</div>',
        unsafe_allow_html=True,
    )


def risk_badge(level, label):
    st.markdown(
        f'<div class="aml-badge aml-badge-{escape(level)}">{escape(label)}</div>',
        unsafe_allow_html=True,
    )


# =========================
# 5. SHAP EXPLAINABILITY
# =========================
@st.cache_resource
def get_shap_explainer(_model):
    return shap.TreeExplainer(_model)


explainer = get_shap_explainer(model)


def get_explanation(row, lang):
    """
    Generate SHAP explanation for one transaction.
    Return top 5 features with original categorical values where possible.
    """
    safe_row = row.copy().reindex(columns=X_train.columns, fill_value=0)
    safe_row = safe_row.astype(X_train.dtypes.to_dict())

    vals = explainer.shap_values(safe_row)

    if isinstance(vals, list):
        vals = vals[1]

    explanation = []

    for feat, val in sorted(
        zip(safe_row.columns, vals[0]),
        key=lambda x: abs(x[1]),
        reverse=True
    )[:5]:

        display_value = safe_row[feat].values[0]

        if feat in encoders:
            try:
                display_value = encoders[feat].inverse_transform(
                    [int(display_value)]
                )[0]
            except Exception:
                display_value = safe_row[feat].values[0]

        if feat in ["is_cross_border", "is_currency_mismatch"]:
            display_value = yn(display_value, lang)

        direction = tr("increases_risk", lang) if val > 0 else tr("reduces_risk", lang)
        icon = "🔴" if val > 0 else "🟢"

        explanation.append({
            "feature": feat,
            "feature_label": FEATURE_LABELS[lang].get(feat, feat),
            "value": display_value,
            "impact": float(val),
            "direction": direction,
            "icon": icon
        })

    return explanation


# =========================
# 6. STR REPORT GENERATION
# =========================
def select_sample(df, condition, fallback_idx=0):
    matches = df[condition(df)]
    if matches.empty:
        return df.iloc[fallback_idx]
    return matches.iloc[0]


@st.cache_data
def build_sample_transactions(df):
    sample_cols = [
        "Time", "Sender_account", "Receiver_account", "Amount",
        "Payment_currency", "Received_currency",
        "Sender_bank_location", "Receiver_bank_location",
        "Payment_type", "Is_laundering"
    ]
    sample_df = df[sample_cols].copy()
    sample_df["Time"] = pd.to_datetime(sample_df["Time"], format="%H:%M:%S", errors="coerce")
    sample_df = sample_df.dropna(subset=["Time"])
    sample_df["hour"] = sample_df["Time"].dt.hour.astype(int)
    sample_df["is_cross_border"] = (
        sample_df["Sender_bank_location"] != sample_df["Receiver_bank_location"]
    ).astype(int)
    sample_df["is_currency_mismatch"] = (
        sample_df["Payment_currency"] != sample_df["Received_currency"]
    ).astype(int)
    sample_df["fan_out_count"] = sample_df.groupby("Sender_account")["Receiver_account"].transform("nunique")
    sample_df["fan_in_count"] = sample_df.groupby("Receiver_account")["Sender_account"].transform("nunique")

    fan_in = sample_df["fan_in_count"] >= 3
    fan_out = sample_df["fan_out_count"] >= 3
    sample_df["Transaction Pattern"] = np.select(
        [
            fan_in & ~fan_out,
            fan_out & ~fan_in,
            fan_in & fan_out,
        ],
        ["fan_in", "fan_out", "fan_in_out"],
        default="normal_flow",
    )

    normal = select_sample(
        sample_df,
        lambda x: (
            (x["Is_laundering"] == 0)
            & (x["is_cross_border"] == 0)
            & (x["is_currency_mismatch"] == 0)
        ),
    )
    cross_border = select_sample(
        sample_df,
        lambda x: (x["is_cross_border"] == 1) | (x["is_currency_mismatch"] == 1),
        fallback_idx=1,
    )
    laundering = select_sample(sample_df, lambda x: x["Is_laundering"] == 1, fallback_idx=2)

    samples = {
        "normal": normal.to_dict(),
        "cross_border": cross_border.to_dict(),
        "laundering": laundering.to_dict(),
    }
    samples["normal"].update({
        "Sender_name": "Harbour Retail Ltd",
        "Receiver_name": "North Street Grocers",
    })
    samples["cross_border"].update({
        "Sender_name": "Global Horizon Trade",
        "Receiver_name": "Westbridge Imports",
    })
    samples["laundering"].update({
        "Sender_name": "Blue Nile Trading",
        "Receiver_name": "Golden Crescent Exchange",
    })
    return samples


def option_index(options, value):
    try:
        return list(options).index(value)
    except ValueError:
        return 0


def build_model_row(
    amount,
    payment_currency,
    received_currency,
    sender_loc,
    receiver_loc,
    payment_type,
    hour,
    fan_in_count,
    fan_out_count,
    transaction_pattern,
):
    log_amount = np.log1p(amount)
    is_round_amount = int((amount % 1000 == 0) or (amount % 10000 == 0))
    is_cash_payment = int(payment_type in ["Cash Deposit", "Cash Withdrawal"])
    high_risk_currencies = ["Moroccan dirham", "Dirham"]
    is_high_risk_currency = int(
        payment_currency in high_risk_currencies or received_currency in high_risk_currencies
    )
    is_cross_border_val = int(sender_loc != receiver_loc)
    is_currency_mismatch_val = int(payment_currency != received_currency)

    row = pd.DataFrame([{
        "Amount": amount,
        "Payment_currency": encoders["Payment_currency"].transform([payment_currency])[0],
        "Received_currency": encoders["Received_currency"].transform([received_currency])[0],
        "Sender_bank_location": encoders["Sender_bank_location"].transform([sender_loc])[0],
        "Receiver_bank_location": encoders["Receiver_bank_location"].transform([receiver_loc])[0],
        "Payment_type": encoders["Payment_type"].transform([payment_type])[0],
        "hour": hour,
        "is_cross_border": is_cross_border_val,
        "is_currency_mismatch": is_currency_mismatch_val,
        "fan_in_count": fan_in_count,
        "fan_out_count": fan_out_count,
        "Transaction Pattern": encoders["Transaction Pattern"].transform([transaction_pattern])[0],
        # Phase 1-2 new features
        "log_amount": log_amount,
        "is_round_amount": is_round_amount,
        "is_cash_payment": is_cash_payment,
        "is_high_risk_currency": is_high_risk_currency,
        "hour_sin": math.sin(2 * math.pi * hour / 24),
        "hour_cos": math.cos(2 * math.pi * hour / 24),
        "cross_border_x_amount": is_cross_border_val * log_amount,
        "currency_mismatch_x_amount": is_currency_mismatch_val * log_amount,
        "cross_border_and_mismatch": is_cross_border_val * is_currency_mismatch_val,
    }])

    # Fill any missing columns from training with 0
    for col in X_train.columns:
        if col not in row.columns:
            row[col] = 0

    row = row[[col for col in X_train.columns]]
    row = row.reindex(columns=X_train.columns)
    return row.astype(X_train.dtypes.to_dict())

def generate_str(
    sender_account,
    receiver_account,
    sender_name,
    receiver_name,
    row,
    risk_score,
    risk_level_label,
    triggered_rules,
    relationship_label,
    transfer_category_label,
    hkd_amount,
    screening_result,
    sender_profile,
    receiver_profile,
    explanation,
    priority,
    deadline,
    priority_reason,
    lang
):
    explanation_text = "\n".join([
        f"- {item['feature_label']}: {item['value']} | {item['direction']} "
        f"({tr('impact', lang)} {item['impact']:.3f})"
        for item in explanation
    ])
    best_match = screening_result["best_match"]
    party_label = party_display(best_match["party"], lang)
    screening_status = screening_label(screening_result, lang)
    screening_next_step = screening_action(screening_result, lang)
    if triggered_rules:
        rules_text = "\n".join([
            f"- {rule['title']} | {rule['action']}"
            for rule in triggered_rules
        ])
    else:
        rules_text = f"- {tr('rules_clear', lang)}"

    if lang == "zh":
        return f"""
可疑交易風險報告草稿

生成時間：{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

一、交易摘要
- 付款方帳戶：{sender_account}
- 付款方名稱：{sender_name}
- 付款方客戶 ID：{sender_profile.get("customer_id", "N/A")}
- 付款方 KYC 風險：{sender_profile.get("kyc_risk_level", "Unknown")}
- 付款方 PEP 狀態：{sender_profile.get("pep_status", "Unknown")}
- 收款方帳戶：{receiver_account}
- 收款方名稱：{receiver_name}
- 收款方客戶 ID：{receiver_profile.get("customer_id", "N/A")}
- 收款方 KYC 風險：{receiver_profile.get("kyc_risk_level", "Unknown")}
- 收款方 PEP 狀態：{receiver_profile.get("pep_status", "Unknown")}
- 交易金額：{row["Amount"]:,.2f}
- 港元等值金額：{hkd_amount:,.2f}
- 客戶關係：{relationship_label}
- 交易類別：{transfer_category_label}
- 交易時間：{int(row["hour"])}:00
- 是否跨境：{yn(row["is_cross_border"], lang)}
- 付款與收款幣種是否不同：{yn(row["is_currency_mismatch"], lang)}

二、香港硬編碼規則引擎
{rules_text}

三、制裁名單篩查
- 篩查結果：{screening_status}
- 命中方：{party_label}
- 名單名稱：{best_match["matched_name"] or "N/A"}
- 匹配分數：{best_match["score"]}
- 名單來源：{best_match["list_source"] or "N/A"}
- 風險類型：{best_match["risk_type"] or "N/A"}
- 建議：{screening_next_step}

四、系統判斷
- 校準後模型警示分數：{risk_score:.3f}
- 風險等級：{risk_level_label}
- 審查優先級：{priority}
- 建議審查期限：{deadline.strftime("%Y-%m-%d %H:%M")}
- 優先原因：{priority_reason}
- 分數說明：此分數用於排序和優先審查，不代表交易一定違規。

五、為什麼需要審查
系統把此交易與歷史樣本中的一般及可疑交易模式比較後，發現若干因素較值得注意。以下是最主要的影響因素：
{explanation_text}

六、建議下一步
- 核對付款方與收款方的客戶資料、交易目的及資金來源。
- 若交易觸發香港硬性規則、制裁名單可能命中、跨境、幣種差異或異常帳戶流向，建議補充收集佐證文件。
- 由合規人員結合 KYC、制裁名單、PEP 名單及內部政策作最終判斷。

七、重要說明
本報告由 MVP v0.1 產生，屬於決策支援工具，不代表自動提交監管申報。目前制裁篩查使用 demo 名單和模糊匹配，正式環境仍需接入官方或商業制裁資料源；最終處理結果需由合規人員覆核。
""".strip()

    return f"""
Draft Suspicious Transaction Risk Report

Generated time: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

1. Transaction Summary
- Sender account: {sender_account}
- Sender name: {sender_name}
- Sender customer ID: {sender_profile.get("customer_id", "N/A")}
- Sender KYC risk: {sender_profile.get("kyc_risk_level", "Unknown")}
- Sender PEP status: {sender_profile.get("pep_status", "Unknown")}
- Receiver account: {receiver_account}
- Receiver name: {receiver_name}
- Receiver customer ID: {receiver_profile.get("customer_id", "N/A")}
- Receiver KYC risk: {receiver_profile.get("kyc_risk_level", "Unknown")}
- Receiver PEP status: {receiver_profile.get("pep_status", "Unknown")}
- Transaction amount: {row["Amount"]:,.2f}
- HKD equivalent amount: {hkd_amount:,.2f}
- Customer relationship: {relationship_label}
- Transaction category: {transfer_category_label}
- Transaction hour: {int(row["hour"])}:00
- Cross-border transaction: {yn(row["is_cross_border"], lang)}
- Currency mismatch: {yn(row["is_currency_mismatch"], lang)}

2. Hong Kong Hardcoded Rules Engine
{rules_text}

3. Sanction Screening
- Screening result: {screening_status}
- Matched party: {party_label}
- Matched list name: {best_match["matched_name"] or "N/A"}
- Match score: {best_match["score"]}
- List source: {best_match["list_source"] or "N/A"}
- Risk type: {best_match["risk_type"] or "N/A"}
- Recommended action: {screening_next_step}

4. System Decision
- Calibrated model alert score: {risk_score:.3f}
- Risk level: {risk_level_label}
- Review priority: {priority}
- Suggested review deadline: {deadline.strftime("%Y-%m-%d %H:%M")}
- Priority reason: {priority_reason}
- Score note: This score is used for ranking and review priority. It does not mean the transaction is definitely unlawful.

5. Why This Needs Review
The system compared this transaction with historical normal and suspicious transaction patterns. The following factors had the strongest influence:
{explanation_text}

6. Recommended Next Steps
- Check the sender and receiver profiles, transaction purpose, and source of funds.
- If the transaction triggers Hong Kong hardcoded rules, a possible sanctions match, cross-border activity, currency mismatch, or unusual account flow, request supporting documents.
- A compliance officer should combine this result with KYC, sanctions, PEP, and internal policy checks before making a final decision.

7. Important Note
This report is generated by MVP v0.1 as a decision-support output, not an automatic regulatory filing. The current sanctions screening uses a demo list and fuzzy matching; production use should connect to official or commercial sanctions sources. Final action must be reviewed by a compliance officer.
""".strip()


# =========================
# 7. UI
# =========================
language_name = st.sidebar.selectbox("Language / 語言", list(LANGUAGES.keys()), index=0)
lang = LANGUAGES[language_name]

st.sidebar.header(tr("module_subscription", lang))
st.sidebar.caption(tr("module_subscription_note", lang))
enabled_modules = {
    "kyc": st.sidebar.checkbox(tr("module_kyc", lang), value=True),
    "transaction_monitoring": st.sidebar.checkbox(
        tr("module_transaction_monitoring", lang),
        value=True,
    ),
    "sanctions": st.sidebar.checkbox(tr("module_sanctions", lang), value=True),
    "str": st.sidebar.checkbox(tr("module_str", lang), value=True),
    "manual_review": st.sidebar.checkbox(tr("module_manual_review", lang), value=True),
}

render_hero(lang)

sample_transactions = build_sample_transactions(raw_df)
sanctions_df = load_sanctions_data()
kyc_df = load_kyc_profiles()

tab1, tab2, tab3 = st.tabs([
    tr("tab_analysis", lang),
    tr("tab_summary", lang),
    tr("tab_doc", lang)
])


# =========================
# TAB 1: TRANSACTION ANALYSIS
# =========================
with tab1:
    section_label(tr("sample_header", lang))
    st.caption(tr("sample_help", lang))

    sample_options = {
        tr("sample_normal", lang): "normal",
        tr("sample_cross_border", lang): "cross_border",
        tr("sample_laundering", lang): "laundering",
    }
    selected_sample_label = st.selectbox(
        tr("sample_header", lang),
        list(sample_options.keys()),
        label_visibility="collapsed",
    )
    sample = sample_transactions[sample_options[selected_sample_label]]

    preview_cols = st.columns(4)
    preview_cols[0].metric(tr("amount", lang), f"{float(sample['Amount']):,.2f}")
    preview_cols[1].metric(tr("sender_location", lang), sample["Sender_bank_location"])
    preview_cols[2].metric(tr("receiver_location", lang), sample["Receiver_bank_location"])
    preview_cols[3].metric(tr("payment_type", lang), sample["Payment_type"])

    st.info(tr("manual_entry", lang))
    section_label(tr("input_header", lang))

    col1, col2 = st.columns(2)
    key_suffix = f"{lang}_{sample_options[selected_sample_label]}"

    with col1:
        sender_account = st.text_input(
            tr("sender_account", lang),
            value=str(sample["Sender_account"]),
            key=f"sender_{key_suffix}",
        )
        sender_name = st.text_input(
            tr("sender_name", lang),
            value=str(sample["Sender_name"]),
            key=f"sender_name_{key_suffix}",
        )
        receiver_account = st.text_input(
            tr("receiver_account", lang),
            value=str(sample["Receiver_account"]),
            key=f"receiver_{key_suffix}",
        )
        receiver_name = st.text_input(
            tr("receiver_name", lang),
            value=str(sample["Receiver_name"]),
            key=f"receiver_name_{key_suffix}",
        )

        amount = st.number_input(
            tr("amount", lang),
            min_value=0.0,
            value=float(sample["Amount"]),
            step=100.0,
            key=f"amount_{key_suffix}",
        )

        hkd_amount = st.number_input(
            tr("hkd_equivalent_amount", lang),
            min_value=0.0,
            value=float(sample["Amount"]),
            step=1000.0,
            key=f"hkd_amount_{key_suffix}",
        )

        hour = st.slider(
            tr("hour", lang),
            0,
            23,
            int(sample["hour"]),
            key=f"hour_{key_suffix}",
        )

    with col2:
        payment_type = st.selectbox(
            tr("payment_type", lang),
            encoders["Payment_type"].classes_,
            index=option_index(encoders["Payment_type"].classes_, sample["Payment_type"]),
            key=f"payment_type_{key_suffix}",
        )

        relationship_options = {
            tr("existing_customer", lang): "existing_customer",
            tr("occasional_non_customer", lang): "occasional_non_customer",
        }
        relationship_label = st.selectbox(
            tr("relationship_status", lang),
            list(relationship_options.keys()),
            key=f"relationship_{key_suffix}",
        )
        relationship_status = relationship_options[relationship_label]

        transfer_category_options = {
            tr("other_transaction", lang): "other_transaction",
            tr("wire_transfer", lang): "wire_transfer",
            tr("virtual_asset_transfer", lang): "virtual_asset_transfer",
        }
        transfer_category_label = st.selectbox(
            tr("transfer_category", lang),
            list(transfer_category_options.keys()),
            key=f"transfer_category_{key_suffix}",
        )
        transfer_category = transfer_category_options[transfer_category_label]

        sender_loc = st.selectbox(
            tr("sender_location", lang),
            encoders["Sender_bank_location"].classes_,
            index=option_index(encoders["Sender_bank_location"].classes_, sample["Sender_bank_location"]),
            key=f"sender_loc_{key_suffix}",
        )

        receiver_loc = st.selectbox(
            tr("receiver_location", lang),
            encoders["Receiver_bank_location"].classes_,
            index=option_index(encoders["Receiver_bank_location"].classes_, sample["Receiver_bank_location"]),
            key=f"receiver_loc_{key_suffix}",
        )

        payment_currency = st.selectbox(
            tr("payment_currency", lang),
            encoders["Payment_currency"].classes_,
            index=option_index(encoders["Payment_currency"].classes_, sample["Payment_currency"]),
            key=f"payment_currency_{key_suffix}",
        )

        received_currency = st.selectbox(
            tr("received_currency", lang),
            encoders["Received_currency"].classes_,
            index=option_index(encoders["Received_currency"].classes_, sample["Received_currency"]),
            key=f"received_currency_{key_suffix}",
        )
        fan_in_count = st.number_input(
            tr("fan_in", lang),
            min_value=0,
            value=int(sample["fan_in_count"]),
            step=1,
            key=f"fan_in_{key_suffix}",
        )

        fan_out_count = st.number_input(
            tr("fan_out", lang),
            min_value=0,
            value=int(sample["fan_out_count"]),
            step=1,
            key=f"fan_out_{key_suffix}",
        )

        transaction_pattern = st.selectbox(
            tr("transaction_pattern", lang),
            encoders["Transaction Pattern"].classes_,
            index=option_index(encoders["Transaction Pattern"].classes_, sample["Transaction Pattern"]),
            key=f"transaction_pattern_{key_suffix}",
        )

    if enabled_modules["kyc"]:
        sender_profile = get_kyc_profile(sender_account, kyc_df)
        receiver_profile = get_kyc_profile(receiver_account, kyc_df)
        section_label(tr("entity_view", lang))
        st.caption(tr("kyc_link_note", lang))
        render_profile_card(tr("sender_account", lang), sender_profile, lang)
        render_profile_card(tr("receiver_account", lang), receiver_profile, lang)
    else:
        sender_profile = empty_kyc_profile(sender_account)
        receiver_profile = empty_kyc_profile(receiver_account)
        section_label(tr("entity_view", lang))
        st.info(tr("module_disabled", lang))

    section_label(tr("transaction_view", lang))

    st.sidebar.header(tr("threshold_settings", lang))
    alert_threshold = st.sidebar.slider(
        tr("alert_threshold", lang),
        min_value=0.0,
        max_value=1.0,
        value=DEFAULT_ALERT_THRESHOLD,
        step=0.05
    )

    high_threshold = st.sidebar.slider(
        tr("high_threshold", lang),
        min_value=0.0,
        max_value=1.0,
        value=DEFAULT_HIGH_THRESHOLD,
        step=0.05
    )

    critical_threshold = st.sidebar.slider(
        tr("critical_threshold", lang),
        min_value=0.0,
        max_value=1.0,
        value=DEFAULT_CRITICAL_THRESHOLD,
        step=0.05
    )

    if not alert_threshold < high_threshold < critical_threshold:
        st.sidebar.warning(
            "請保持門檻順序：警示 < 高風險 < Critical"
            if lang == "zh"
            else "Keep thresholds ordered: alert < high < critical"
        )

    st.sidebar.markdown(tr("priority_logic", lang))

    if st.button(tr("analyze", lang)):

        with st.spinner(tr("analyzing", lang)):

            row = build_model_row(
                amount,
                payment_currency,
                received_currency,
                sender_loc,
                receiver_loc,
                payment_type,
                hour,
                fan_in_count,
                fan_out_count,
                transaction_pattern,
            )
            if enabled_modules["transaction_monitoring"]:
                risk_score = scoring_model.predict_proba(row)[0][1]
                model_risk_level = get_risk_level(
                    risk_score,
                    alert_threshold,
                    high_threshold,
                    critical_threshold,
                )
            else:
                risk_score = 0.0
                model_risk_level = "low"

            if enabled_modules["sanctions"]:
                sender_screening_name = profile_name(sender_profile, sender_name)
                receiver_screening_name = profile_name(receiver_profile, receiver_name)
                screening_result = screen_sanctions(
                    sender_screening_name,
                    receiver_screening_name,
                    sanctions_df,
                )
            else:
                screening_result = no_screening_result()

            risk_level = model_risk_level
            if enabled_modules["sanctions"]:
                risk_level = apply_sanction_override(risk_level, screening_result)
            if enabled_modules["kyc"]:
                risk_level = apply_kyc_override(
                    risk_level,
                    sender_profile,
                    receiver_profile,
                )
            triggered_rules = evaluate_hk_rules(
                hkd_amount,
                relationship_status,
                transfer_category,
                lang,
            )
            risk_level = apply_rules_override(risk_level, triggered_rules)
            risk_level_label = tr(risk_level, lang)
            screening_result_label = screening_label(screening_result, lang)
            st.session_state["last_analysis"] = {
                "sender_account": sender_account,
                "receiver_account": receiver_account,
                "risk_score": float(risk_score),
                "original_risk_level": risk_level,
                "current_risk_level": risk_level,
                "screening_status": screening_result["status"],
                "triggered_rules": ",".join([rule["code"] for rule in triggered_rules]),
                "analysis_time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            }

        score_col, level_col, screening_col = st.columns(3)
        score_col.metric(tr("risk_score", lang), f"{risk_score:.3f}")
        level_col.metric(tr("risk_level", lang), risk_level_label)
        screening_col.metric(tr("screening_result", lang), screening_result_label)
        risk_badge(risk_level, risk_level_label)
        st.caption(tr("score_note", lang))
        st.caption(tr("screening_note", lang))

        section_label(tr("rules_engine", lang))
        st.caption(tr("rules_note", lang))
        if triggered_rules:
            for rule in triggered_rules:
                st.warning(f"{rule['title']}: {rule['action']}")
        else:
            st.success(tr("rules_clear", lang))

        if enabled_modules["sanctions"]:
            section_label(tr("sanction_screening", lang))
            best_match = screening_result["best_match"]
            st.write(screening_action(screening_result, lang))
            screen_cols = st.columns(4)
            screen_cols[0].metric(tr("matched_party", lang), party_display(best_match["party"], lang))
            screen_cols[1].metric(tr("matched_name", lang), best_match["matched_name"] or "N/A")
            screen_cols[2].metric(tr("match_score", lang), best_match["score"])
            screen_cols[3].metric(tr("risk_type", lang), best_match["risk_type"] or "N/A")
        else:
            section_label(tr("sanction_screening", lang))
            st.info(tr("module_disabled", lang))

        if risk_level == "low":
            st.success(tr("no_alert", lang))
            st.info(tr("no_alert_explain", lang))

        else:
            st.error(tr("alert", lang))

            priority, deadline, priority_reason = get_priority_for_level(
                risk_level,
                lang,
                screening_result,
                sender_profile,
                receiver_profile,
            )

            explanation = get_explanation(row, lang)

            col_a, col_b, col_c, col_d = st.columns(4)
            col_a.metric(tr("risk_level", lang), risk_level_label)
            col_b.metric(tr("priority", lang), priority)
            col_c.metric(tr("deadline", lang), deadline.strftime("%Y-%m-%d %H:%M"))
            col_d.metric(tr("priority_reason", lang), priority_reason)

            section_label(tr("why_flagged", lang))
            st.caption(tr("plain_explanation_intro", lang))

            for item in explanation:
                impact_text = f"{item['impact']:.3f}"

                if item["impact"] > 0:
                    st.error(
                        f"{item['icon']} **{item['feature_label']}** = `{item['value']}`\n\n"
                        f"{tr('impact', lang)}: `{impact_text}` | {item['direction']}"
                    )
                else:
                    st.success(
                        f"{item['icon']} **{item['feature_label']}** = `{item['value']}`\n\n"
                        f"{tr('impact', lang)}: `{impact_text}` | {item['direction']}"
                    )

            if enabled_modules["str"]:
                report = generate_str(
                    sender_account=sender_account,
                    receiver_account=receiver_account,
                    sender_name=sender_name,
                    receiver_name=receiver_name,
                    row=row.iloc[0],
                risk_score=risk_score,
                risk_level_label=risk_level_label,
                triggered_rules=triggered_rules,
                relationship_label=relationship_label,
                transfer_category_label=transfer_category_label,
                hkd_amount=hkd_amount,
                screening_result=screening_result,
                sender_profile=sender_profile,
                    receiver_profile=receiver_profile,
                    explanation=explanation,
                    priority=priority,
                    deadline=deadline,
                    priority_reason=priority_reason,
                    lang=lang
                )

                st.text_area(tr("report_label", lang), report, height=520)
            else:
                section_label(tr("report_label", lang))
                st.info(tr("module_disabled", lang))

    if enabled_modules["manual_review"] and "last_analysis" in st.session_state:
        section_label(tr("manual_intervention", lang))
        st.caption(tr("manual_intervention_note", lang))

        analysis = st.session_state["last_analysis"]
        override_cols = st.columns(3)
        override_cols[0].metric(
            tr("original_level", lang),
            risk_level_display(analysis["original_risk_level"], lang),
        )
        override_cols[1].metric(
            tr("final_level", lang),
            risk_level_display(analysis["current_risk_level"], lang),
        )
        override_cols[2].metric(
            tr("risk_score", lang),
            f"{analysis['risk_score']:.3f}",
        )

        manager_col, role_col = st.columns(2)
        manager_name = manager_col.text_input(tr("manager_name", lang), key="override_manager_name")
        manager_role = role_col.text_input(
            tr("manager_role", lang),
            value="Senior Manager",
            key="override_manager_role",
        )

        options = risk_level_options(lang)
        current_label = risk_level_display(analysis["current_risk_level"], lang)
        selected_label = st.selectbox(
            tr("override_level", lang),
            list(options.keys()),
            index=list(options.keys()).index(current_label),
            key="override_level_select",
        )
        override_reason = st.text_area(
            tr("override_reason", lang),
            key="override_reason_text",
            height=90,
        )

        if st.button(tr("apply_override", lang), key="apply_manual_override"):
            if not manager_name.strip() or not override_reason.strip():
                st.warning(tr("override_reason_required", lang))
            else:
                new_level = options[selected_label]
                append_audit_record({
                    "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    "manager_name": manager_name.strip(),
                    "manager_role": manager_role.strip(),
                    "sender_account": analysis["sender_account"],
                    "receiver_account": analysis["receiver_account"],
                    "original_risk_level": analysis["current_risk_level"],
                    "new_risk_level": new_level,
                    "risk_score": f"{analysis['risk_score']:.3f}",
                    "reason": override_reason.strip(),
                })
                st.session_state["last_analysis"]["current_risk_level"] = new_level
                load_audit_trail.clear()
                st.success(tr("override_saved", lang))

        section_label(tr("audit_trail", lang))
        audit_df = load_audit_trail()
        if audit_df.empty:
            st.info(tr("audit_trail", lang) + ": N/A")
        else:
            st.dataframe(audit_df.tail(10).iloc[::-1], use_container_width=True)
    elif "last_analysis" in st.session_state:
        section_label(tr("manual_intervention", lang))
        st.info(tr("module_disabled", lang))


# =========================
# TAB 2: MODEL / DATASET SUMMARY
# =========================
with tab2:
    section_label(tr("dataset_used", lang))
    st.write("Dataset: `SAML-D.csv`")
    st.write(tr("dataset_note", lang))

    section_label(tr("training_strategy", lang))

    col1, col2, col3 = st.columns(3)

    with col1:
        st.write(tr("balanced_training", lang))
        st.write(metrics["train_distribution"])

    with col2:
        st.write(tr("calibration_distribution", lang))
        st.write(metrics["calibration_distribution"])

    with col3:
        st.write(tr("real_test", lang))
        st.write(metrics["test_distribution"])

    st.markdown(tr("design_choice", lang))

    section_label(tr("model", lang))
    st.write(tr("algorithm", lang))

    section_label(tr("metrics", lang))
    metric_col1, metric_col2, metric_col3, metric_col4 = st.columns(4)
    metric_col1.metric("Recall", f"{metrics['recall']:.3f}", help=tr("recall_help", lang))
    metric_col2.metric("Precision", f"{metrics['precision']:.3f}")
    metric_col3.metric("F1 Score", f"{metrics['f1']:.3f}")
    metric_col4.metric("AUPRC", f"{metrics['auprc']:.3f}", help="Area Under Precision-Recall Curve")
    st.caption(tr("recall_help", lang))
    st.caption(tr("calibration_help", lang))

    # Additional operational metrics
    op_col1, op_col2, op_col3 = st.columns(3)
    op_col1.metric("Alert Rate", f"{metrics['alert_rate']:.1f}%", help="% of all test transactions flagged as alert")
    op_col2.metric("Training Samples", f"{metrics['num_train_samples']:,}", help="Number of samples used for model training")
    op_col3.metric("Sampling Ratio", f"{metrics['sampling_ratio']}:1", help="Normal:Fraud ratio after undersampling")

    st.write(f"{metrics['calibration_method']} | Alert threshold used for evaluation: {metrics['evaluation_threshold']:.2f}")

    st.text(tr("classification_report", lang))
    st.code(metrics["classification_report"])


# =========================
# TAB 3: MVP TEST DOCUMENT
# =========================
with tab3:
    section_label(tr("tab_doc", lang))
    st.markdown(tr("test_doc", lang))
